{# include the svg sprite for icons used with icomoon #}
{% if site.icomoon %}
  <!-- Modify here -->
  <!-- This is the list of all icons supported -->
  <!-- If an icon is missing you can add from https://icomoon.io/ -->
  <!-- Create a new set of icons with the Icomoon App then Generate SVG. Copy the contents of the SVG here -->
  <!-- You can remove the ones you don't need but you don't have too, your site performance is not affected if they are left here -->
  {% include '../../../../framework/structure/icomoon/icomoon-sprite.svg' %}
{% endif %}
